name = "firebird"
author = "sonosive"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b42dbf1c6c1f8b09c8bb44166b9507efa82f20f1f8743de41700da1cb06c5d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
